import type { Metadata } from "next";

import { ChakraProviders } from "@/components/provider/ChakraProvider";
import { fonts } from "@/libs/font";

import "./globals.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={fonts.rubik.variable}>
        <ChakraProviders>{children} </ChakraProviders>
      </body>
    </html>
  );
}
